from homeassistant.const import Platform

DOMAIN = "ziggo_modem"

CONF_HOST = "host"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_VERBOSE_DIAGNOSTICS = "verbose_diagnostics"
CONF_LANGUAGE = "language"
CONF_DOWNSTREAM_POWER_MIN = "downstream_power_min"
CONF_DOWNSTREAM_POWER_MAX = "downstream_power_max"
CONF_DOWNSTREAM_SNR_MIN = "downstream_snr_min"
CONF_UPSTREAM_POWER_MAX = "upstream_power_max"

DEFAULT_HOST = "192.168.100.1"
DEFAULT_PORT = 443
DEFAULT_SCAN_INTERVAL = 60
DEFAULT_VERBOSE_DIAGNOSTICS = False
DEFAULT_LANGUAGE = "nl"
DEFAULT_DOWNSTREAM_POWER_MIN = -10.0
DEFAULT_DOWNSTREAM_POWER_MAX = 10.0
DEFAULT_DOWNSTREAM_SNR_MIN = 34.0
DEFAULT_UPSTREAM_POWER_MAX = 52.0
LANGUAGE_EN = "en"
LANGUAGE_NL = "nl"
LANGUAGE_OPTIONS = [LANGUAGE_NL, LANGUAGE_EN]

PLATFORMS: list[Platform] = [
    Platform.SENSOR,
    Platform.BUTTON,
    Platform.SWITCH,
    Platform.BINARY_SENSOR,
]
